### ISSUE TITLE
The entire bar looks pixelated/blurry.

### ISSUE THREAD

**Issue by Ahnaf-Zaman** [Droptop-Four/Basic-Version#16]
I have used droptop for a while and didn't face such problems until now. The bar looks blurry and pixelated. I have it scaled to 100% but it looks bigger than it should. I am using Windows 11 Insider Edition and Droptop Version 4.303.
![image](https://user-images.githubusercontent.com/73687469/161044124-b2c9da01-588d-4877-bd20-8e44f1fa7fa4.png)

**Comment by notAperson535** [comment]
@bayleaf0 Do you use a 4k display? If so, the bar is blurry because high dpi is off.

**Comment by bayleaf0** [comment]
> @bayleaf0 Do you use a 4k display? If so, the bar is blurry because high dpi is off.

No, its a 1080p display.

**Comment by notAperson535** [comment]
ok, than just try restarting rainmeter. you could also try this: https://forum.rainmeter.net/viewtopic.php?t=22272

**Comment by bayleaf0** [comment]
> ok, than just try restarting rainmeter. you could also try this: https://forum.rainmeter.net/viewtopic.php?t=22272

Still didn't work, unfortunately. Also, the Windows scaling option from the forum post was already on by default.

**Comment by notAperson535** [comment]
> > ok, than just try restarting rainmeter. you could also try this: https://forum.rainmeter.net/viewtopic.php?t=22272
> 
> Still didn't work, unfortunately. Also, the Windows scaling option from the forum post was already on by default.

ok, then I don't really know. Just try reinstalling droptop base version and maybe even reinstall rainmeter

**Comment by 66Bunz** [comment]
@bayleaf0 were you able to solve this problem?

**Comment by 66Bunz** [comment]
closed for inactivity
