### ISSUE TITLE
I was trying to uninstall droptop four because it stopped working, then when I stopped rainmeter and tried to delete the file, it keeps saying that the file is open in an app. when I checked task manager, there was no apps running and I cannot delete it. Please Advise me on what to do.

### ISSUE THREAD

**Issue by YEETPLAYZGT** [Droptop-Four/Basic-Version#17]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 66Bunz** [comment]
@YEETPLAYZGT it's possible that there was the `Droptop Rainmeter.exe` app still running.

**Comment by techpowerxxs** [comment]
close rainmeter in task manager then un-install if this does not work its because you have chosen to always have droptop in the back ground so you have to uninstall rainmeter then uninstall droptop then re-install rainmeter *if you are still gonna use it for skins*
