### ISSUE TITLE
Problem with the app drower icon

### ISSUE THREAD

**Issue by Freyja335** [Droptop-Four/Basic-Version#19]
when i click on the icon to see my background apps it does not open any menu, it does nothing
![Screenshot 2022-05-22 011854](https://user-images.githubusercontent.com/92382538/169670741-455e6a5d-8750-4331-a1b1-fa62ad553284.png)

**Comment by 66Bunz** [comment]
In our [discord server](https://discord.gg/aGQ6uE4Fgp) there is a possible fix for this issue!

**Comment by Niko7887** [comment]
Where is this fix? I'm on that Discord server but I cannot find it..

**Comment by 66Bunz** [comment]
https://discord.com/channels/800124057923485728/1023886381900116009
