### ISSUE TITLE
The writing showing the app i'm using doesn't work

### ISSUE THREAD

**Issue by NixPlayer** [Droptop-Four/Basic-Version#20]
when I change the app the writing showing which app I am on does not work and the name of the app I was using before is still written (for example: I open discord and start rainmeter, in that case the writing is correct, I close discord and open file explorer and discord still shows. I try another app and it does the same). Please fix
![La scritta che mostra l'app che sto usando non funziona!

**Comment by 66Bunz** [comment]
If you try to restart your pc it should fix itself.

**Comment by NixPlayer** [comment]
it doesn't work. I have the latest version of droptop and it's very annoying, because i have a "mac os custom" personalization on  windows 11 and having this bug it's bad. Please fix this with an update

**Comment by 66Bunz** [comment]
@NixPlayer I suggest u to download the last version, it should be solved by now
