### ISSUE TITLE
A white bar in the bottom of the bar

### ISSUE THREAD

**Issue by John123CoolHelpMien** [Droptop-Four/Basic-Version#24]
A White Bar Is At The Bottom Of The Bar And Blocks My Screen.
![Screenshot (211)](https://user-images.githubusercontent.com/108935841/177991669-1738eb99-e4b8-4a35-afcf-4657a30a12f5.png)

**Comment by 66Bunz** [comment]
That's probably a problem with the blur under the bar or the shadows. Try to disable them in the droptop settings and check.

**Comment by John123CoolHelpMien** [comment]
Ok Thanks!

**Comment by John123CoolHelpMien** [comment]
OMG IT WORKS THANK YOU!
