### ISSUE TITLE
ERROR SELECTING AUDIO DEVICE

### ISSUE THREAD

**Issue by VIXI0** [Droptop-Four/Basic-Version#26]
**Describe the bug**
as you can see in the image below the audio device is not the one that I select:
this is probably because is listing a Bluetooth devices that are not connected.

**To Reproduce**
1.connect an audio device Bluetooth
2.disconnect de device
3. Go to 'SPEAKER ICON'
4. Click on 'AUDIO DEVICE'
3. TRY SELECTING DE DEFAULT AUDIO DEVICE

**Expected behavior**
To select the audio device that i clicked

**Screenshots**
![image](https://user-images.githubusercontent.com/43118641/179756301-55047978-0c82-4f55-8806-d34d42ef68aa.png)

**Desktop (please complete the following information):**
 - OS: WIN11
 - Version [4.306.4]

**Comment by VIXI0** [comment]
problem present in the latest version

**Comment by Cariboudjan** [comment]
I'm aware of this issue. No known solution at the moment. Audio devices are pulled from device manager, which means any device that has ever been connected to the PC will display here, but the numbers associated with each name change.

**Comment by VIXI0** [comment]
![image](https://user-images.githubusercontent.com/43118641/180517607-503ae6b4-8456-4cfa-9670-f1d3d9a22ef3.png)
![image](https://user-images.githubusercontent.com/43118641/180517666-574d38f5-80f4-41a7-aca0-952a8dc98bc4.png)

I don't know the language, platform or library that you used to develop this, but inf you can access the device status and only list devices that doesn't contain the status _DN_DEVICE_DISCONNECTED_ will be more than enough. 

or create an event listener so when a device in connected or disconnected you update the list with its numbers.

(As I said before its just a suggestion bcz i don't know the development method, I hope this produce a spark to find the solution and does not remove this great feature)

**Comment by VIXI0** [comment]
Fixed in  [4.307.6]
