### ISSUE TITLE
App drawer not working

### ISSUE THREAD

**Issue by UdDReX** [Droptop-Four/Basic-Version#27]
I have been facing this problem where even after clicking the "App Drawer" icon, it does nothing for few days now. Something similar happened where after clicking the Home Icon nothing seems to happen. So I reinstalled and now its working but the App Drawer not working after that.

**Comment by 66Bunz** [comment]
In our [discord server] (https://discord.gg/aGQ6uE4Fgp) we have a solution for that problem. Try that.
