### ISSUE TITLE
the droptop installation assistant isnt working

### ISSUE THREAD

**Issue by Whaleguy5533** [Droptop-Four/Basic-Version#28]
**Describe the bug**
i installed "droptop basic version" and ran it with rainmeter and theres an installation assistant but all it does it have 1 button then it closes

**To Reproduce**
run droptop basic version.rmskin

**Expected behavior**
i think theres supposed to be an installation where u pick your language and etc
**Screenshots**
not really necessary 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version idk latest? i only just downloaded it

**Smartphone (please complete the following information):**
 - Device: why is this important? (motorola moto g 10)
 - OS: android 11 i think
 - Browser firefox
 - Version i dont have it on mobile

**Additional context**

**Comment by 66Bunz** [comment]
If you can, please come to our Discord server where we can help you more directly and easily. [Droptop Four Official Discord Server](https://discord.com/invite/jbxcmfn2vZ)
