### ISSUE TITLE
App drawer doesnt work

### ISSUE THREAD

**Issue by GiorgosAthanasopoulos** [Droptop-Four/Basic-Version#3]
When i try to open the app drawer to see minimized apps i get a busy mouse pointer for 1 sec and nothing happens after that

**Comment by 66Bunz** [comment]
@giorgos-athanassopoulos come to the [Droptop Four Official Discord](https://discord.com/invite/jbxcmfn2vZ) Server where we posted a temporary solution before it will be completely solved
