### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by jeffy7b** [Droptop-Four/Basic-Version#31]
**Describe the bug**
When I click on the download link, an error page is displayed which is shown below

**Screenshots**
![Screenshot (144)](https://user-images.githubusercontent.com/110490837/182447227-6a6384b5-ae84-4897-a84c-0bb2bb3d66b0.png)

**Comment by 66Bunz** [comment]
The link should work fine, I just tried it. Try to reload your page and click again.
