### ISSUE TITLE
Languages not appearing

### ISSUE THREAD

**Issue by VzEugen** [Droptop-Four/Basic-Version#32]
**Describe the bug**
I enabled the Input language feature in droptop and it shows nothing but the icon of this feature. On my pc I have enabled these inputs: English (US), Russian (Russia).

**To Reproduce**
1. Enabling input language in droptop
2. Not showing the language

**Expected behavior**
Instead of appearing the icon of input language, should show the currently enabled language

**Screenshots**
![image](https://user-images.githubusercontent.com/103501985/184613203-606023df-8343-4dce-8dae-7b6baac2e05f.png)

**Additional context**

**Diagnostic (please go to the Droptop Four settings > Support > Developer Tools > Diagnostic to Clipboard and paste them under here):**

**Comment by Cariboudjan** [comment]
Not really bug, more of a suggestion - But I'll look into this.
