### ISSUE TITLE
Droptop loaded but not showing up

### ISSUE THREAD

**Issue by Tung1312** [Droptop-Four/Basic-Version#33]
Never having issue with Droptop before, only after install the latest update, Droptop isn't showing up after I turn on the laptop despite still loaded in Rainmeter

I tried to re-install Droptop but still not showing up after I restart my laptop

I don't what to expect cuz i'm a total noob at coding things

![image](https://user-images.githubusercontent.com/113844686/190912768-5acbb89d-873d-434a-b884-b96ba1b4c7b5.png)
![image](https://user-images.githubusercontent.com/113844686/190912973-efe5041d-f676-43cc-b3b4-f8bce1285996.png)

I'm using Asus TUF 15 with Window 11

I can't get the Diagnostic be cuz Droptop isn't show up
(sr for bad English + new Github user)

**Comment by 66Bunz** [comment]
This could be a problem with the new AppBar plugin, if you join our discord server you'll find a solution as soon there will be one!!

<p align="center">
  <a href="https://discord.gg/aGQ6uE4Fgp" target="_blank">
    <img src="https://discordapp.com/api/guilds/800124057923485728/widget.png?style=banner3" alt="Discord Community Invite"/>
  </a>
</p>

**Comment by 66Bunz** [comment]
The problem should be solvable installing the latest rainmeter update, since there was a bug with the previous version
