### ISSUE TITLE
Droptop-Four keeps crashing after using it, or making changes.

### ISSUE THREAD

**Issue by 1Breaker** [Droptop-Four/Basic-Version#34]
**Describe the bug**
It crashes after using any feature or changing the settings, then it also re-scales itself and it's now off-set.

**To Reproduce**
1. Clean install Droptop-Four
2. Edit the settings true the bar itself
3. Crash

**Expected behavior**
I expect the bar not to crash Rainmeter everytime I use it.

**Screenshots**
![image](https://user-images.githubusercontent.com/113736895/191362531-718cce43-e28e-4fcd-9869-56f348f38385.png)

**Additional context**
Nothing else, it just crashes. I installed the bar, it was working fine for a few seconds and poof crash.

**Diagnostic (please go to the Droptop Four settings > Support > Developer Tools > Diagnostic to Clipboard and paste them under here):**
__**OS information**__

- OS: Windows 11 x64
- OSVERSION: 11
- Win10Apps: 0

__**Rainmeter information**__

- Skins path: %USERPROFILE%\Documents\Rainmeter\Skins\

- Program drive: C:
- Program path: C:\Program Files\Rainmeter\
- Settings path: %USERPROFILE%\AppData\Roaming\Rainmeter\
- Plugins path: C:\Program Files\Rainmeter\Plugins\
- Addons path: %USERPROFILE%\AppData\Roaming\Rainmeter\Addons\
- Config editor: C:\Program Files\WindowsApps\Microsoft.WindowsNotepad_10.2102.13.0_x64__8wekyb3d8bbwe\Notepad\Notepad.exe

__**Monitor information**__

- Primary screen area: 0, 0, 1920, 1080
- Screen area: 0, 0, 1920, 1080

- Primary work area: 0, 31, 1920, 1001
- Work area: 0, 31, 1920, 1001

- Virtual screen area: -1920, 0, 3840, 1080

- Droptop on monitor: Primary

__**Droptop information**__

- Droptop version: 4.308.2
- Build date: 0911.1328

- Height of top bar: 31
- Droptop scale: 1.2

- Droptop display mode: Always Show

**Comment by 66Bunz** [comment]
It was a rainmeter bug that was solved with the latest update, so please install the latest rainmeter update
