### ISSUE TITLE
Droptop crashes when opening Samsung Notes

### ISSUE THREAD

**Issue by waghehe** [Droptop-Four/Basic-Version#35]
I don't know if you can really do something about it, maybe it's a problem from the samsung notes app but everytime I open samsung notes on my laptop, droptop 4 crashes and I have to open Rainmeter again. The problem only appplies to Droptop. Other things I use with rainmeter don't crash except ModularClocks from JaxCore

1. Install Droptop
2. Install Samsung Notes from the Microsoft Store
3. Open Samsung Notes 
4. Droptop crashes

__**OS information**__

- OS: Windows 10 x64
- OSVERSION: 10
- Win10Apps: 1

__**Rainmeter information**__

- Skins path: %USERPROFILE%\Documents\Rainmeter\Skins\

- Program drive: C:
- Program path: C:\Program Files\Rainmeter\
- Settings path: %USERPROFILE%\AppData\Roaming\Rainmeter\
- Plugins path: C:\Program Files\Rainmeter\Plugins\
- Addons path: %USERPROFILE%\AppData\Roaming\Rainmeter\Addons\
- Config editor: C:\Windows\system32\NOTEPAD.EXE

__**Monitor information**__

- Primary screen area: 0, 0, 1920, 1080
- Screen area: 0, 0, 1920, 1080

- Primary work area: 0, 0, 1920, 1040
- Work area: 0, 0, 1920, 1040

- Virtual screen area: 0, 0, 1920, 1080

- Droptop on monitor: Primary

__**Droptop information**__

- Droptop version: 4.308.2
- Build date: 0911.1328

- Height of top bar: 26
- Droptop scale: 1.0

- Droptop display mode: Desktop Only

**Comment by 66Bunz** [comment]
Try to install the latest rainmeter update, there was a bug in the previous version of it
