### ISSUE TITLE
Change folder name

### ISSUE THREAD

**Issue by natan-lee** [Droptop-Four/Basic-Version#36]
When i try and change the name of a folder, i right click it. However, it gives me the option to change the name of a different folder

**To Reproduce**
1. right click a folder
2. click on "folder settings'
3. click 'rename ______'

**Screenshots**
![image](https://user-images.githubusercontent.com/108373446/191702872-b3339e43-695c-4ac7-8ba9-0d3c5487e19e.png)
 In this screenshot, i right clicked on Controls

**Additional context**

**Diagnostic (please go to the Droptop Four settings > Support > Developer Tools > Diagnostic to Clipboard and paste them under here):**

**Comment by 66Bunz** [comment]
You are right, this is a new bug, thanks for make us notice it.
If you want to change a name of a folder you can also open droptop settings > My Folders > select the folder you want to change the name to > Rename.
This second way should work.

**Comment by natan-lee** [comment]
yes it does, thanks!!

**Comment by 66Bunz** [comment]
With the latest update this problem should be fixed, try it from https://github.com/Droptop-Four/Update/releases/tag/Update
