### ISSUE TITLE
Desktop visible & hoverable bar

### ISSUE THREAD

**Issue by crqch** [Droptop-Four/Basic-Version#37]
Add an mode for:
- while in Desktop, always show
- while in fullscreen apps, hover to show

Would be useful as sometimes I'd like to use it on fullscreen apps, e.x. to open an app, but also like having it always displayed on desktop (for clock, weather status etc.)

**Comment by 66Bunz** [comment]
U need to put droptop on desktop, and then enable `Settings > Options > Menu options > Accessibility in full screen apps` to be able to use it with fullscreen apps

**Comment by crqch** [comment]
> U need to put droptop on desktop, and then enable `Settings > Options > Menu options > Accessibility in full screen apps` to be able to use it with fullscreen apps

I'm making a feature request, not wanting help. As said, mode for visibility of Droptop, where it's always visible on desktop and maximized apps, and hoverable while on fullscreen apps. Take windows bar for example. It's always visible, apart from fullscreen apps.

**Comment by 66Bunz** [comment]
What you want probably can already be done with this setting here

> U need to put droptop on desktop, and then enable `Settings > Options > Menu options > Accessibility in full screen apps` to be able to use it with fullscreen apps

**Comment by crqch** [comment]
> What you want probably can already be done with this setting here
> 
> > U need to put droptop on desktop, and then enable `Settings > Options > Menu options > Accessibility in full screen apps` to be able to use it with fullscreen apps
> 
> 

it won't, as I want to have hoverable and permanent droptop at the same time, not either of those modes

**Comment by 66Bunz** [comment]
@crqch Try the latest droptop version
