### ISSUE TITLE
Missing the app Tray icon (downward arrow) 

### ISSUE THREAD

**Issue by yAya-yns** [Droptop-Four/Basic-Version#38]
Hi,

I am missing the app trap icon there. I tried around and couldn't find where to turn it on. Please refer to the screenshot below.

Btw, would there be ways to remove the icons from the droptop bar? (ex. the JaxCore icon, recent files icon, etc.)

Thanks

![image](https://user-images.githubusercontent.com/33261653/193467153-04e949f7-a2ec-4ab8-b672-39e5e5d8cce5.png)

**Comment by crqch** [comment]
Right click on either of the icons to manage their order aswell as toggle them. Screenshot for reference
![image](https://user-images.githubusercontent.com/48185508/193639376-4a127ffc-2866-4feb-82d7-a20e1a61d074.png)

**Comment by yAya-yns** [comment]
Thank you!
