### ISSUE TITLE
Feature: Add in an actual Global Menu

### ISSUE THREAD

**Issue by rbreaves** [Droptop-Four/Basic-Version#4]
I know this might be a big request, but I know this ViDock app by Lee-soft had figured out how to recreate File menu bars for various applications dynamically. Would there be any possibility of porting that type of work into an official dll for use within this theme? ViDock is very broken and I think it'd make a lot of sense to port part of how it works into rainmeter via a dll extension.

https://github.com/lee-soft/ViDock

Also I am the author of kinto.sh, an app the lets you have mac-style shortcut keys in Windows and Linux, hence my own interest in using this rainmeter skin.

**Comment by giovannidias1** [comment]
+1

**Comment by Verisimilitude11** [comment]
+1

**Comment by notAperson535** [comment]
@rbreaves There would have to be a rainmeter plugin to do this

**Comment by rbreaves** [comment]
Oh I know, I discussed it in their discord awhile back. No one seemed that interested & I’ve not had the time or interest to learn Rainmeter well enough to create a DLL plugin for this type of feature myself.

I use Linux most of the time any ways, still it’d be a very nice addition to see & make transitioning btwn Windows & Mac as seamless as Mac & Linux for the most part.

**Comment by rbreaves** [comment]
I am aware, regardless I posted it here in hopes there'd be interest and increased demand for it over time. I strongly disagree with their position that is not worth the time - it most certainly is even if the developer(s) involved don't appreciate that feature. It is very unfortunate imo as it would be immensely useful, if not the single most useful feature of this entire application or mod, whatever you want to call it.

**Comment by notAperson535** [comment]
> I am aware, regardless I posted it here in hopes there'd be interest and increased demand for it over time. I strongly disagree with their position that it is not worth the time - it most certainly is even if the developer(s) involved don't appreciate that feature. It is very unfortunate imo as it would be immensely useful, if not the single most useful feature of this entire application or mod, whatever you want to call it.
> 
> In lieu of this feature being available/written though I have just settled for running Windows inside of a VM and forgetting that this app even exists - it literally serves no purpose for me since I now run Linux first and everything else via xfreerdp clients maximized with singular apps that I need to access per monitor. I really don't have to think much about anything since I limit my use of the Windows OS and only run the apps I absolutely need to run on those systems.
> 
> I basically get to keep my global menus intact besides the few Windows apps I run maximized.

In order for this to happen, someone has to create a rainmeter plugin that can do this.
