### ISSUE TITLE
Minor issue with menu backgrounds

### ISSUE THREAD

**Issue by adrian5683** [Droptop-Four/Basic-Version#41]
Hi all, been using this for a while now and I love everything about it, save for a minor annoyance which I can't figure out how to fix.
In the image below you can see there's a white border drawn at the top of each menu background. What you can't see is every once in a while it flickers slightly. It happens only when I open a menu and then goes away. Any idea what could be causing this border to be drawn in white? Thanks in advance.
![Capture](https://user-images.githubusercontent.com/47461694/195175726-3d9dd7f8-8b19-43d0-9a21-03e98fb83034.png)

**Comment by 66Bunz** [comment]
try to remove the blur of the menus

**Comment by adrian5683** [comment]
That did it, thanks!
