### ISSUE TITLE
Droptop 4 isnt running on Windows 7

### ISSUE THREAD

**Issue by skittlebee32** [Droptop-Four/Basic-Version#42]
Droptop 4 is just straight up not working on Windows 7. Can you devs maybe make one for Windows 7? Thanks

**Comment by 66Bunz** [comment]
Win7 is no more supported by droptop four. If you want to use it in win7 you need to download an older version

**Comment by skittlebee32** [comment]
> Win7 is no more supported by droptop four. If you want to use it in win7 you need to download an older version
Thanks for the info. I will be upgrading to Windows 10 now (not because Droptop).

Have a beer, takioki
