### ISSUE TITLE
the app drawer keeps opening my taskbar

### ISSUE THREAD

**Issue by baradomaa** [Droptop-Four/Basic-Version#47]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Diagnostic (please go to the Droptop Four settings > Support > Developer Tools > Diagnostic to Clipboard and paste them under here):**

**Comment by 66Bunz** [comment]
is this still happening with the latest version?

**Comment by Tauriz** [comment]
> is this still happening with the latest version?

Yep, still happens on freshly installed Windows 11 22H2 25262.1000.

**Comment by 66Bunz** [comment]
@Tauriz I meant the latest droptop version
