### ISSUE TITLE
Droptop bar not aligning to top

### ISSUE THREAD

**Issue by 3prm3** [Droptop-Four/Basic-Version#48]
![image](https://user-images.githubusercontent.com/70713233/202885298-ef9127ea-64cf-4410-902f-c52f086e404e.png)
How to reproduce: change the positions of your monitors

I've tried changing the monitor it's on and pressing the fix button but it only works temporarily

**Comment by 66Bunz** [comment]
> How to reproduce: change the positions of your monitors

by changing the positions of the monitors you mean if you change the positions of the monitors in the win settings with already droptop enabled?

**Comment by 3prm3** [comment]
Yes

**Comment by 3prm3** [comment]
I did a reinstall of Droptop too

**Comment by 3prm3** [comment]
The bar still doesn't go to the proper position

**Comment by 3prm3** [comment]
(I downloaded the latest build)

**Comment by 66Bunz** [comment]
that's probably a bug with a plugin droptop uses, but right now we're waiting the developer to return and fix some things

**Comment by 3prm3** [comment]
Ok

**Comment by 3prm3** [comment]
I've deleted the entire Droptop folder

**Comment by 3prm3** [comment]
It didn't fix itself

**Comment by Cariboudjan** [comment]
Hello @3prm3 . I have found the cause of the issue, and reinstalling would not have helped. This was definitely an issue with the app. The issue is now resolved. Please download the update [here](https://github.com/Droptop-Four/Update/releases/tag/Update). The problem should now be resolved.

**Comment by 3prm3** [comment]
Thank you so much for fixing this quickly
