### ISSUE TITLE
App drawer can't work

### ISSUE THREAD

**Issue by qiankemeng** [Droptop-Four/Basic-Version#51]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem [here.]

**Diagnostic (please go to the Droptop Four settings > Support > Developer Tools > Diagnostic to Clipboard and paste them under here):**

https://user-images.githubusercontent.com/68374326/212310754-f9d918a4-478b-4e64-812b-f1855409923a.mp4

**Comment by 66Bunz** [comment]
@qiankemeng have you tried to see if the tray is open under the chrome tab?

**Comment by qiankemeng** [comment]
Sure, I have tried many times.

**Comment by 66Bunz** [comment]
try to select a different button from here `Droptop settings >> App settings >> App drawer`

**Comment by qiankemeng** [comment]
All of them not work

**Comment by qiankemeng** [comment]
I think it might be because my system is beta

**Comment by 66Bunz** [comment]
Could be.
Can you specify your windows version?

**Comment by qiankemeng** [comment]
![image](https://user-images.githubusercontent.com/68374326/212554961-938e9e16-44c6-4768-a231-832ab1ac8ec0.png)

**Comment by 66Bunz** [comment]
Yeah, probably cause you are on the Insider program
