### ISSUE TITLE
Droptop website not loading

### ISSUE THREAD

**Issue by Bloo-Snoc** [Droptop-Four/Basic-Version#52]
When i try to go to the droptop website, it doesn't load. 
![image](https://user-images.githubusercontent.com/92127849/215424223-c9e70f34-df90-48ed-a1a6-851767b10abb.png)

**Comment by 66Bunz** [comment]
That's a problem with your dns provider. You might want to change your dns record and try again

**Comment by Bloo-Snoc** [comment]
> That's a problem with your dns provider. You might want to change your dns record and try again

how
