### ISSUE TITLE
action center button and app drawer button not working. What to do?

### ISSUE THREAD

**Issue by NikhilCodes04** [Droptop-Four/Basic-Version#54]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Diagnostic (please go to the Droptop Four settings > Support > Developer Tools > Diagnostic to Clipboard and paste them under here):**

**Comment by NikhilCodes04** [comment]
After latest windows update maybe

**Comment by 66Bunz** [comment]
@NikhilCodes04 
Are you on the beta channel of win11?

Are you using some apps that modify your taskbar like startallback or others?

**Comment by changtse** [comment]
Hello, I just updated to windows 11 and started using droptop four, and i want the app drawer to open the system tray icons, but i don't know how to configure "button 1, 2, etc" and i'm not sure if it is related to this problem.

**Comment by 66Bunz** [comment]
check if any of that setting can show the system tray

**Comment by sleepingdz** [comment]
I have the same problem the 3 dots for the system tray is not showing anything.

**Comment by 66Bunz** [comment]
Microsoft with the new Moment 2 update redesigned both the logic and the appereances of the system tray, so there is not a solution to this problem yet. 
We are working on creating a droptop tray to replicate the system tray.

**Comment by A-little-hedgehog** [comment]
> Microsoft with the new Moment 2 update redesigned both the logic and the appereances of the system tray, so there is not a solution to this problem yet. We are working on creating a droptop tray to replicate the system tray.

Thank you, i was getting this issue too. Hope you can easily fix it

**Comment by modelme66** [comment]
I have the same problem the 3 dots for the system tray is not showing anything, too !

**Comment by edgarcnp** [comment]
Same here, hope the feature will be fixed soon.

**Comment by 66Bunz** [comment]
@NikhilCodes04 @edgarcnp @changtse @A-little-hedgehog @antieksi @modelme66 @sleepingdz 
Update to the latest droptop version, if you are on the latest win11 version, right click on the tray, activate the option `Use legacy App Drawer` and the option `Triggers Win+B shortcut`.

We hope we can find a way to integrate it better in the future

**Comment by edgarcnp** [comment]
> @NikhilCodes04 @edgarcnp @changtse @A-little-hedgehog @antieksi @modelme66 @sleepingdz Update to the latest droptop version, if you are on the latest win11 version, right click on the tray, activate the option `Use legacy App Drawer` and the option `Triggers Win+B shortcut`.
> 
> We hope we can find a way to integrate it better in the future

Hey, thanks for the quick response. Just want to let you know that the given instructions solves the problem.

**Comment by modelme66** [comment]
Thanks a lot...
