### ISSUE TITLE
[Request] A few adjustments

### ISSUE THREAD

**Issue by Cyberdr3am** [Droptop-Four/Basic-Version#57]
Hello and thank you for this very good application. I would like to make some suggestions regarding various things that I would like to add to the bar.

- To be able to shift the inscriptions from the left and from the right towards the center at a certain percentage (I have a large screen and I have the information that will find it on the right and on the left which is complicated to watch)
- Display the percentage used at the level of the Cpu / Ram and Gpu icons to allow a quick overview of the percentage used and not to have to click on it each time.
- It would be nice to be able to move the icons on the bar as we see fit to be able to reorganize them with spaces and to be able to put things in the middle of the bar for example.
- I would like if possible to be able to divide the bar in two because I have a dock and therefore leave room for the dock and have the bar on each side of the dock.
- I don't know if this is possible but it would be nice to be able to integrate notifications directly below the bar like that of windows but to be able to customize them.
- Finally I would like to be able to have the support of the virtual screen created with display fusion (A large screen will be cut into three parts but the bar does not take into account the 3 parts but the whole screen)

Thanks in advance

**Comment by Cariboudjan** [comment]
> To be able to shift the inscriptions from the left and from the right towards the center at a certain percentage (I have a large screen and I have the information that will find it on the right and on the left which is complicated to watch)

As Bunz said, "Try this Droptop settings >> Options >> Menu options >> Top bar centering"

> Display the percentage used at the level of the Cpu / Ram and Gpu icons to allow a quick overview of the percentage used and not to have to click on it each time.

The Usage Monitor app will display your CPU, RAM, GPU usage percentages in the form of 3 icons.

> It would be nice to be able to move the icons on the bar as we see fit to be able to reorganize them with spaces and to be able to put things in the middle of the bar for example.

You can rearrange apps and folders by right-clicking on them and changing their position in the dropdown menu. Use "Droptop settings >> Options >> Shape >> Divide bar into sections" and then put a centered dock, like Nexus dock, at the top-middle of Droptop to get this functionality.

> I would like if possible to be able to divide the bar in two because I have a dock and therefore leave room for the dock and have the bar on each side of the dock.

Try "Droptop settings >> Options >> Shape >> Divide bar into sections"

> I don't know if this is possible but it would be nice to be able to integrate notifications directly below the bar like that of windows but to be able to customize them.

Droptop notifications are integrated into the bar itself, making use of the empty space in the center of the bar.

> Finally I would like to be able to have the support of the virtual screen created with display fusion (A large screen will be cut into three parts but the bar does not take into account the 3 parts but the whole screen)

Top bar centering should be able to do essentially this without needing to add any extra feature.

**Comment by Cyberdr3am** [comment]
Thanks a lot for your answers.
Regarding the offset of the bar, it works very well. This during the bar is cut on each side (it does not go to the end of the screen and stops at the level of the text. I would very much like to be able to simply shift the text but let the bar take up the totality of the screen.
Regarding the icons for the use of the computer I have already put the icons on the other hand I cannot see percentage without opening the menu so it would be nice to be able to see it without having to click on it.
Concerning " Divide bar into sections " I have activated it but I cannot freely move the icons and the menus in the bar. I right click on a folder but I can't move it freely.
Regarding the dock even with the activate option I still have the problem with the dock.
Regarding notifications I have no notification from windows or other applications that are at the level of the bar that I will receive one.
As for "Top bar centering" I did not find this option. Can you tell me where it is?
Thanks in advance.
I would also like to know where I can take the donator version to thank you.

**Comment by Cariboudjan** [comment]
Droptop settings
Options
Menu options
Top bar centering

You can move apps and folders by right clicking on them and using the arrows
