### ISSUE TITLE
Desktop navigator not updating properly

### ISSUE THREAD

**Issue by SirPhilip3** [Droptop-Four/Basic-Version#60]
**Describe the bug**
Desktop navigator is not updating when using the default windows shortcut or the desktop manager in the taskbar

**To Reproduce**
1. Create a new Desktop using Ctrl+Win+D
2. Switch to it using Ctrl+Win+righ arrow key 
3. See error

**Expected behavior**
Desktop navigator should update it's status when i change desktop using windows shortcut / the taskbar desktop manager

**Screenshots**
Desktop navigator showing that i'm in Desktop 1 
![Screenshot (13)](https://user-images.githubusercontent.com/118560349/227733669-9f0cf895-969a-4021-b2f2-5c7df96fcc37.png)
Current Desktop: Desktop 6
![Screenshot (14)](https://user-images.githubusercontent.com/118560349/227733674-032b23df-0cf3-4544-af8c-a50429b42cdb.png)

**Additional context**

**Diagnostic (please go to the Droptop Four settings > Support > Developer Tools > Diagnostic to Clipboard and paste them under here):**

**Comment by Cariboudjan** [comment]
I'll be updating Droptop soon to fix this functionality.

**Comment by Cariboudjan** [comment]
Please see the beta update for this fix:
https://discord.com/channels/800124057923485728/801786468426973185
