### ISSUE TITLE
Droptop Four caught by Easy Anti-Cheat engine

### ISSUE THREAD

**Issue by BanditPrince** [Droptop-Four/Basic-Version#61]
Whenever I start a game that uses the Easy Anti-Cheat with Droptop Four on, it marks my system as cheating. Once I exit Droptop it stops giving this error. I've attached the error in case it's any help:
![image](https://user-images.githubusercontent.com/106791216/228838462-54920bdd-92c1-4b8d-8815-fb4b2887befa.png)

**Comment by Cariboudjan** [comment]
It's because of AutoHotkey. The only suggestion I have is to enable Game Mode.
![Annotation 2023-03-31 120607](https://user-images.githubusercontent.com/75376803/229196765-731a0a93-87f2-4375-b6aa-9429829c4e7f.png)
