### ISSUE TITLE
DropTop crashes immedietly as I start up Rainmeter.

### ISSUE THREAD

**Issue by theEpicjosh** [Droptop-Four/Basic-Version#63]
**Describe the bug**
Every time I try to open Rainmeter while Droptop is selected as a skin, it crashes as soon as I start it up.

**To Reproduce**
Open Rainmeter bandit should crash immediately.

**Expected behavior**
DropTop is to be running normally.

**Screenshots**
No screenshots. There is nothing to screenshot.

**Additional context**
I have tried holding "Ctrl" to reset the Rainmeter skins and starting DropTop that way.
I have also tried deleting and reinstalling DropTop.
Both solutions did not work.

This has happened either at random or I have no idea how it would've happened.

**Diagnostic (please go to the Droptop Four settings > Support > Developer Tools > Diagnostic to Clipboard and paste them under here):**
I cannot as Rainmeter crashes immediately as I start DropTop.

**Comment by theEpicjosh** [comment]
Sorry. I had fixed this issue. It apparently had something to do with the WebNowPlaying module.

**Comment by 66Bunz** [comment]
Okok
