### ISSUE TITLE
Center time format bug

### ISSUE THREAD

**Issue by ineedtolearnhowtocode** [Droptop-Four/Basic-Version#65]
**Describe the bug**
Unable to select format 1 in "change center time format" dropdown menu.

**Expected behavior**
I click the first option but the tick doesn't darken meaning that my clicking isn't actually choosing the setting. The weird thing is that in the "change time format" dropdown, I can choose format 1 fine.

I've managed to solve the issue by manually setting the center time format to 1 in the UserSettings.inc file within Droptop variables but I thought you should know that the option was not responisive within the app's dropdown for me. Using English - UK language on Windows 11.

Also, I know this is a bug report but would you consider changing the date format of the mm/ddyy option to dd/mm/yy for English - UK? Here in the UK dd/mm/yy is used 99.9% of the time so it'd be great for that to be reflected for the English - UK option.

Thanks :)

**Diagnostic:**

__**OS information**__

- OS: Windows 11 x64
- OSVERSION: 11
- Win10Apps: 0

__**Rainmeter information**__

- Skins path: %USERPROFILE%\Documents\Rainmeter\Skins\

- Program drive: C:
- Program path: C:\Program Files\Rainmeter\
- Settings path: %USERPROFILE%\AppData\Roaming\Rainmeter\
- Plugins path: C:\Program Files\Rainmeter\Plugins\
- Addons path: %USERPROFILE%\AppData\Roaming\Rainmeter\Addons\

__**Monitor information**__

- Primary screen area: 0, 0, 1920, 1080
- Screen area: 0, 0, 1920, 1080

- Primary work area: 0, 0, 1920, 1080
- Work area: 0, 0, 1920, 1080

- Virtual screen area: 0, 0, 1920, 1080

- Droptop on monitor: Primary

__**Droptop information**__

- Droptop version: 4.320.7.0
- Build date: 23.0508

- Height of top bar: 30
- Droptop scale: 1.0
- Currently using theme: Transparent

- Droptop display mode: Auto-hide
- Accessibility in fullscreen: 1

__**App information**__

✅ Disks-Phan
❌ Quick_Settings-Cariboudjan
❌ Usage_Monitor-Cariboudjan
❌ Daily_Quotes-Bunz
❌ Sample_App-Cariboudjan

**Comment by 66Bunz** [comment]
fixed in the latest droptopfour version @ineedtolearnhowtocode
