### ISSUE TITLE
[Bug]: Droptop bar sticks when hovered over when using fullscreen app after minimizing another app

### ISSUE THREAD

**Issue by ineedtolearnhowtocode** [Droptop-Four/Basic-Version#66]
### What happened?

hard to describe but the droptop bar at the top sticks (when it is meant to go away). This is using the auto-hide function of Droptop.

I managed to reproduce it by opening Firefox, pressing F11 to go fullscreen, and opening any other small-window tab (like Steam). Press on Steam to set focus, then press the minimize button, and then move the cursor up to the top of the screen to reveal Droptop, then move the cursor away. 

Droptop should then disappear but instead it doesn't. Even when clicking on the fullscreen Firefox to ensure focus, Droptop stays at the top. 

To get rid of Droptop after this has happened, I open the battery icon on Droptop, then press back onto Firefox.

### What should have happened?

After minimizing the small window and revealing Droptop, when I move the mouse away droptop should hide.

### Diagnostics

```shell
__**OS information**__

- OS: Windows 11 x64
- OSVERSION: 11
- Win10Apps: 0

__**Rainmeter information**__

- Skins path: %USERPROFILE%\Documents\Rainmeter\Skins\

- Program drive: C:
- Program path: C:\Program Files\Rainmeter\
- Settings path: %USERPROFILE%\AppData\Roaming\Rainmeter\
- Plugins path: C:\Program Files\Rainmeter\Plugins\
- Addons path: %USERPROFILE%\AppData\Roaming\Rainmeter\Addons\

__**Monitor information**__

- Primary screen area: 0, 0, 1920, 1080
- Screen area: 0, 0, 1920, 1080

- Primary work area: 0, 0, 1920, 1080
- Work area: 0, 0, 1920, 1080

- Virtual screen area: 0, 0, 1920, 1080

- Droptop on monitor: Primary

__**Droptop information**__

- Droptop version: 4.320.9.0
- Build date: 23.0509

- Height of top bar: 30
- Droptop scale: 1
- Currently using theme: Transparent

- Droptop display mode: Auto-hide
- Accessibility in fullscreen: 1

__**App information**__

❌ Disks-Phan
❌ Quick_Settings-Cariboudjan
❌ Usage_Monitor-Cariboudjan
❌ Daily_Quotes-Bunz
❌ Sample_App-Cariboudjan
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by 66Bunz** [comment]
Try disabling `Droptop settings >> Options >> Menu options >> Accessibility in fullscreen apps`

**Comment by ineedtolearnhowtocode** [comment]
not really a solution, now I don't see droptop at all even when i hover over the area legitimately. I would like it to be visible on hover in all my apps, just would prefer it not to stick when following the steps to reproduce above.

**Comment by 66Bunz** [comment]
@ineedtolearnhowtocode this problem should be now fixed
