### ISSUE TITLE
Windows version error

### ISSUE THREAD

**Issue by tuncayofficial** [Droptop-Four/Basic-Version#7]
It says droptop four requires Windows 7 ort later and I have Windows 7 Ultimate, but it gives an error.
![image](https://user-images.githubusercontent.com/68643463/142766784-412365e1-79a0-44b6-b5f9-6a8bdadfb94e.png)

**Comment by 66Bunz** [comment]
@tuncayofficial From the version 4.29 Droptop requires Windows 10
