### ISSUE TITLE
Use WebNowPlaying for Spotify and Web

### ISSUE THREAD

**Issue by vvirtues** [Droptop-Four/Basic-Version#9]
[WebNowPlaying](https://github.com/tjhrulz/WebNowPlaying/releases) is much more efficient than scanning spotify manually. Plus, it supports all media functions
![image](https://user-images.githubusercontent.com/81705406/148593557-977d0bee-51b1-47bb-8d49-1ead6b83b005.png)
^Using WebNowPlaying

![image](https://user-images.githubusercontent.com/81705406/148593667-c8b1573e-94b1-445b-a752-f6cd15262037.png)
^Manual Scan

**Comment by 66Bunz** [comment]
> [WebNowPlaying](https://github.com/tjhrulz/WebNowPlaying/releases) is much more efficient than scanning spotify manually. Plus, it supports all media functions

Hey @vvirtues, I absolutely agree with you but not everyone who uses Spotify has Spicetify installed with the webnowplaying plugin.
The `Spotify` Droptop player is usable also without Spicetify and webnowplaying installed, so it will remain as a player for who has only Spotify installed.
